name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    if: contains(github.event.comment.body, 'Julio')
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME 
      - run: echo $GITHUB_ISSUE_COMMENT

      
        
      
