name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo $GITHUB_EVENT_NAME 
      - run: echo ${{ github.event.comment.body }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}


      
        
      
