name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.changes.body }}
      - run: echo ${{ github.event.comment.body }}
      - run: echo ${{ github.event.issues.body }}
        
      - name: Turn comment into file
        run: |
          ID=${{ github.event.comment.id }}
          AUTHOR=${{ github.event.comment.user.login }}
          DATE=${{ github.event.comment.created_at }}
          COMMENT=$(echo "${{ github.event.comment.body }}")
          NO_TAGS=${COMMENT//[<>]/\`}
          FOLDER=comments

          printf '%b\n' "<div class=\"comment\"><p>${AUTHOR} says:</p><p>${NO_TAGS//$'\n'/\<\/p\>\<p\>}</p><p>${DATE}</p></div>\r\n" > ${FOLDER}/${ID}.html
          
      - run: cat ${FOLDER}/${ID}.html
      
