name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME 
      - run: echo ${{ github.event.client_payload.actor }}
      
      - shell: pwsh
        run: if( ${{ github.event.comment.body }} -eq "Julio") {"Sample"} else {"Not"})
      
        
      
