# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: docker pull node:latest
    - run: docker tag node:latest acrsampleaction.azurecr.io/teste:v3
    - name: Push Image to ACR
      uses: julioarruda/pushimagetoacr@v0
      with:
        acr-tokenname: ${{ secrets.ACR_TOKEN_NAME }}
        acr-token: ${{ secrets.ACR_TOKEN }}
        acr-account: acrsampleaction.azurecr.io
        acr-imagename: acrsampleaction.azurecr.io/teste:v2
